"""Add user profile image URL to User model

Revision ID: 357accf600b4
Revises: e99198f04448
Create Date: 2025-05-10 23:40:51.288121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357accf600b4'
down_revision = 'e99198f04448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
