"""Add tournament creation date and start time

Revision ID: 375186703e8d
Revises: 357accf600b4
Create Date: 2025-05-11 10:48:55.072607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375186703e8d'
down_revision = '357accf600b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
