"""Add created_at and start_time to Tournament

Revision ID: ac5b7cd2da81
Revises: 9d81f8044f2b
Create Date: 2025-05-10 23:27:29.265604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5b7cd2da81'
down_revision = '9d81f8044f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('start_time')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
